import turtle
myPen = turtle.Turtle()
myPen.shape("arrow")
myPen.forward(185)
myPen.right(105)
myPen.forward(85)
myPen.right(45)
myPen.forward(65)
myPen.right(55)
myPen.forward(65)
myPen.right(35)
myPen.forward(90)
myPen.color("red")
myPen.delay(5)
